language: php

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

## Install or update dependencies
install:
  - composer validate
  - composer install --prefer-dist
  - composer show

## Run the actual test
script:
  - composer unit --timeout=0
